version: '3.8'

services:
  meu-app:
    build: .
    container_name: meu-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "./public:/home/node/app/public"
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: my-mariadb
    restart: always
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: mariadbPW
      MARIADB_ROOT_PASSWORD: mariadbrootPW
    volumes:
      - "./mariadb-data/data:/var/lib/mysql"
      - "./mariadb-data/logs:/var/log/mysql"
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
